name: Metrics
on:
  schedule:
    - cron: "0 */12 * * *" # Har 12 ghante me update hoga
  workflow_dispatch: # Manually run karne ka option

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rksingh1713
          template: classic
          config_timezone: Asia/Kolkata
